### ISSUE TITLE
How can I see the web application?

### ISSUE THREAD

**Issue by 2jaeeeee** [j-x-huang/Medical-Blockchain#7]

**Comment by 2jaeeeee** [comment]
I succeeded to run web application
But I did 'Add Patient' in admin web , data  is not stored and I can't see  any patient in Get Patients..
help!

**Comment by j-x-huang** [comment]
Please make sure to start the Fabric network (either a single organisation or multi-organisation) before you run the web app. Remember to generate the network card for the admin (automatic if you run the scripts), start the rest server and run the web app on http-server. Please refer to the readme to get the network up and running. Once it is up you should be able to add patients and see them once you have added them. Clicking 'Get Patient' will refresh the data if it's not doing so already.
